param([string]$RepoRoot='C:\dev\assemblelink',[string]$FixturePath='')
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$StateDir=Join-Path $RepoRoot 'state';$ReceiptDir=Join-Path $RepoRoot 'proofs\receipts'
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function WriteUtf8([string]$Path,[string]$Text){EnsureDir (Split-Path -Parent $Path);$normalized=$Text.Replace("`r`n","`n").Replace("`r","`n");if(-not$normalized.EndsWith("`n")){$normalized+="`n"};[IO.File]::WriteAllText($Path,$normalized,(New-Object Text.UTF8Encoding($false)))}
function Sha([string]$Path){$stream=[IO.File]::OpenRead($Path);$sha=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose();$stream.Dispose()}}
function Prop([object]$Object,[string]$Name){if($null-eq$Object){return ''};$property=$Object.PSObject.Properties[$Name];if($null-eq$property-or$null-eq$property.Value){return ''};([string]$property.Value).Trim()}
function Bounded([string]$Value,[int]$Length=512){if($null-eq$Value){return ''};$clean=$Value-replace'[\x00-\x1f\x7f]',' ';$clean.Substring(0,[Math]::Min($Length,$clean.Length))}
function SafeCim([string]$Class){try{@(Get-CimInstance $Class -ErrorAction Stop)}catch{$script:errors+=([ordered]@{source=$Class;status='unavailable'});@()}}
function DriverFor([string]$Name){$key=($Name.ToLowerInvariant()-replace'[^a-z0-9]+',' ').Trim();if($script:signedByName.ContainsKey($key)){return $script:signedByName[$key]};$null}
function NewRecommendation([string]$Id,[string]$Name,[string]$Reason,[string]$Vendor,[string]$Domain,[string]$Direction){[pscustomobject][ordered]@{id=$Id;name=$Name;classification='official_support_path';reason=Bounded $Reason;official_vendor=$Vendor;official_domain=$Domain;official_direction=$Direction;risk='driver_admin_required';install_mode='recommend_only';update_status='not_checked'}}
EnsureDir $StateDir;EnsureDir $ReceiptDir;$errors=@();$signedByName=@{}
if($FixturePath){
  if(-not(Test-Path -LiteralPath $FixturePath -PathType Leaf)){throw 'DRIVER_FIXTURE_MISSING'};$fixture=Get-Content -LiteralPath $FixturePath -Raw|ConvertFrom-Json
  $cs=$fixture.computer_system;$base=$fixture.baseboard;$bios=$fixture.bios;$cpu=$fixture.cpu;$gpus=@($fixture.graphics);$net=@($fixture.network);$sound=@($fixture.audio);$signed=@($fixture.signed_drivers)
}else{
  $cs=@(SafeCim 'Win32_ComputerSystem')|Select-Object -First 1;$base=@(SafeCim 'Win32_BaseBoard')|Select-Object -First 1;$bios=@(SafeCim 'Win32_BIOS')|Select-Object -First 1;$cpu=@(SafeCim 'Win32_Processor')|Select-Object -First 1
  $gpus=@(SafeCim 'Win32_VideoController'|Select-Object -First 16);$net=@(SafeCim 'Win32_NetworkAdapter'|Where-Object{$_.PhysicalAdapter-eq$true}|Select-Object -First 32);$sound=@(SafeCim 'Win32_SoundDevice'|Select-Object -First 32);$signed=@(SafeCim 'Win32_PnPSignedDriver'|Where-Object{$_.DeviceClass-in@('DISPLAY','NET','MEDIA','SYSTEM')}|Select-Object -First 300)
}
foreach($driver in $signed){$key=((Prop $driver 'DeviceName').ToLowerInvariant()-replace'[^a-z0-9]+',' ').Trim();if($key-and-not$signedByName.ContainsKey($key)){$signedByName[$key]=$driver}}
$recommendations=@();$cpuName=Bounded (Prop $cpu 'Name');$boardVendor=Bounded (Prop $base 'Manufacturer');$boardProduct=Bounded (Prop $base 'Product')
if($cpuName-match'AMD'){$recommendations+=(NewRecommendation 'amd-chipset' 'AMD chipset support' 'AMD CPU/platform detected' 'AMD' 'amd.com' 'Review the AMD chipset page and motherboard vendor support page.')}
elseif($cpuName-match'Intel'){$recommendations+=(NewRecommendation 'intel-chipset' 'Intel chipset support' 'Intel CPU/platform detected' 'Intel' 'intel.com' 'Review Intel Driver & Support Assistant and the computer or motherboard vendor support page.')}
foreach($gpu in $gpus){$name=Bounded (Prop $gpu 'Name');if($name-match'NVIDIA'){$recommendations+=(NewRecommendation 'nvidia-driver' 'NVIDIA graphics support' "NVIDIA GPU detected: $name" 'NVIDIA' 'nvidia.com' 'Review NVIDIA official drivers and choose Studio or Game Ready for the workstation role.')}elseif($name-match'AMD|Radeon'){$recommendations+=(NewRecommendation 'amd-adrenalin' 'AMD graphics support' "AMD/Radeon GPU detected: $name" 'AMD' 'amd.com' 'Review AMD Software: Adrenalin Edition on AMD support.')}elseif($name-match'Intel'){$recommendations+=(NewRecommendation 'intel-graphics' 'Intel graphics support' "Intel graphics detected: $name" 'Intel' 'intel.com' 'Review Intel Driver & Support Assistant or the OEM support page.')}}
foreach($adapter in $net){$name=Bounded (Prop $adapter 'Name');if($name-match'Realtek'){$recommendations+=(NewRecommendation 'realtek-network' 'Realtek network support' "Realtek network adapter detected: $name" 'Computer or motherboard vendor' 'vendor-specific' 'Use the computer or motherboard vendor support page first.')}elseif($name-match'Intel'){$recommendations+=(NewRecommendation 'intel-network' 'Intel network support' "Intel network adapter detected: $name" 'Intel' 'intel.com' 'Review Intel Driver & Support Assistant or the OEM support page.')}}
foreach($device in $sound){$name=Bounded (Prop $device 'Name');if($name-match'Realtek'){$recommendations+=(NewRecommendation 'realtek-audio' 'Realtek audio support' "Realtek audio device detected: $name" 'Computer or motherboard vendor' 'vendor-specific' 'Use the computer or motherboard vendor support page first.')}}
$vendorRules=@(@{pattern='ASRock';id='asrock-support';vendor='ASRock';domain='asrock.com'},@{pattern='Micro-Star|MSI';id='msi-support';vendor='MSI';domain='msi.com'},@{pattern='ASUSTeK|ASUS';id='asus-support';vendor='ASUS';domain='asus.com'},@{pattern='Gigabyte';id='gigabyte-support';vendor='GIGABYTE';domain='gigabyte.com'},@{pattern='Dell';id='dell-support';vendor='Dell';domain='dell.com'},@{pattern='Lenovo';id='lenovo-support';vendor='Lenovo';domain='lenovo.com'},@{pattern='HP|Hewlett';id='hp-support';vendor='HP';domain='hp.com'})
foreach($rule in $vendorRules){if($boardVendor-match$rule.pattern){$recommendations+=(NewRecommendation $rule.id "$($rule.vendor) system support" "$boardVendor $boardProduct detected" $rule.vendor $rule.domain 'Use the exact model support page for BIOS, chipset, networking, audio, and utilities.');break}}
function DeviceRow($Device,[string]$FallbackVersion=''){ $name=Bounded (Prop $Device 'Name');$signedDriver=DriverFor $name;[ordered]@{name=$name;manufacturer=Bounded $(if($signedDriver){Prop $signedDriver 'Manufacturer'}else{Prop $Device 'Manufacturer'});driver_version=Bounded $(if($signedDriver){Prop $signedDriver 'DriverVersion'}else{$FallbackVersion});driver_date=Bounded $(if($signedDriver){Prop $signedDriver 'DriverDate'}else{''});device_status=Bounded (Prop $Device 'Status')} }
$runId=[guid]::NewGuid().ToString('n');$observed=(Get-Date).ToUniversalTime();$profile=[ordered]@{schema='assemblelink.driver_profile.v2';run_id=$runId;observed_utc=$observed.ToString('o');observation_status=$(if($errors.Count){'partial'}else{'complete'});safety_policy=[ordered]@{default_install_mode='recommend_only';driver_auto_install_allowed=$false;requires_admin=$true;require_restore_point_before_driver_install=$true;official_vendor_source_required=$true;update_claims_require_provider_verification=$true};platform=[ordered]@{machine_manufacturer=Bounded (Prop $cs 'Manufacturer');machine_model=Bounded (Prop $cs 'Model');motherboard_vendor=$boardVendor;motherboard_product=$boardProduct;bios_vendor=Bounded (Prop $bios 'Manufacturer');bios_version=Bounded (Prop $bios 'SMBIOSBIOSVersion');cpu=$cpuName};graphics=@($gpus|ForEach-Object{DeviceRow $_ (Prop $_ 'DriverVersion')});network=@($net|ForEach-Object{DeviceRow $_});audio=@($sound|ForEach-Object{DeviceRow $_});recommendations=@($recommendations|Sort-Object id -Unique);collection_errors=$errors}
$stamp=$observed.ToString('yyyyMMdd_HHmmss_fffffff');$out=Join-Path $StateDir "driver_profile.$stamp.$runId.json";$latest=Join-Path $StateDir 'driver_profile.latest.json';$json=$profile|ConvertTo-Json -Depth 20;WriteUtf8 $out $json;WriteUtf8 "$out.sha256" ((Sha $out)+'  '+[IO.Path]::GetFileName($out)+"`n");WriteUtf8 $latest $json;WriteUtf8 "$latest.sha256" ((Sha $latest)+'  '+[IO.Path]::GetFileName($latest)+"`n")
$receipt=Join-Path $ReceiptDir "assemblelink.driver_profile_receipt.$stamp.$runId.json";WriteUtf8 $receipt (([ordered]@{schema='assemblelink.driver_profile_receipt.v2';run_id=$runId;observed_utc=$profile.observed_utc;state=[IO.Path]::GetFileName($out);state_sha256=Sha $out;observation_status=$profile.observation_status;recommendations=@($profile.recommendations).Count}|ConvertTo-Json -Depth 6));WriteUtf8 "$receipt.sha256" ((Sha $receipt)+'  '+[IO.Path]::GetFileName($receipt)+"`n");Write-Output $out
